import dotenv from "dotenv";
dotenv.config();

const ANTHROPIC_MODEL_NAME = process.env.ANTHROPIC_MODEL_NAME;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

const PORTAL_CLOUDMERSIVE_API_KEY = process.env.PORTAL_CLOUDMERSIVE_API_KEY;

export { ANTHROPIC_MODEL_NAME, ANTHROPIC_API_KEY, PORTAL_CLOUDMERSIVE_API_KEY };

export const spamWordsList = [
  // Marketing & Sales Spam
  "buy now",
  "free money",
  "click here",
  "visit link",
  "earn $",
  "make money fast",
  "win now",
  "limited offer",
  "subscribe",
  "join now",
  "act now",
  "cheap",
  "guaranteed",
  "risk-free",
  "work from home",
  "hot deal",
  "discount",
  "bonus",
  "instant access",
  "gift card",
  "free trial",
  "order now",
  "shop now",
  "call now",
  "contact us",
  "special offer",
  "exclusive deal",
  "limited time",
  "hurry",
  "don't miss out",
  "act fast",
  "last chance",
  "best price",
  "lowest price",
  "save now",
  "huge savings",
  "free shipping",
  "free delivery",
  "cash back",
  "get rich",
  "easy money",
  "passive income",
  "extra income",
  "side hustle",
  "money maker",
  "investment opportunity",
  "business opportunity",
  "affiliate",
  "mlm",
  "pyramid",
  "network marketing",
  "financial freedom",
  "retire early",
  "financial independence",
  "no experience needed",
  "no experience necessary",
  "no skills required",
  "minimum investment",
  "zero investment",
  "proven system",
  "secret method",
  "hidden trick",
  "little known",
  "insiders know",
  "exclusive access",
  "vip access",
  "premium access",
  "members only",
  "limited spots",
  "limited slots",
  "act now",
  "before it's gone",
  "supplies limited",
  "while supplies last",

  // Profanity & Offensive Words
  "fuck",
  "shit",
  "asshole",
  "bitch",
  "bastard",
  "damn",
  "crap",
  "dick",
  "pussy",
  "cunt",
  "slut",
  "whore",
  "faggot",
  "motherfucker",
  "hell",
  "jerk",
  "douche",
  "piss",
  "ass",
  "bullshit",
  "horseshit",
  "dammit",
  "bloody",
  "bugger",
  "arse",
  "twat",
  "wanker",
  "cock",
  "bollocks",
  "arsehole",
  "sod",
  "bloody hell",
  "damn it",
  "fuck off",
  "fuck you",
  "shit bag",
  "son of a bitch",
  "dumbass",
  "jackass",
  "retard",
  "idiot",
  "moron",
  "bastards",
  "bitches",

  // Suspicious/Phishing Spam
  "verify account",
  "confirm identity",
  "update payment",
  "unusual activity",
  "immediate action required",
  "urgent action needed",
  "click link",
  "confirm now",
  "authenticate",
  "re-enter password",
  "validate",
  "security alert",
  "account suspended",
  "account locked",
  "unauthorized access",
  "suspicious activity",
  "confirm details",
  "update information",
  "reactivate",
  "reactivate account",
  "expired",
  "expired account",
  "action required",
  "verify identity",
  "validate identity",
  "confirm ownership",

  // Health/Medical Spam
  "weight loss",
  "lose weight fast",
  "diet pills",
  "miracle cure",
  "cure",
  "treatment",
  "remedy",
  "health supplement",
  "vitamin",
  "supplement",
  "pharmaceutical",
  "prescription",
  "medication",
  "pills",
  "tablets",
  "capsules",
  "natural remedy",
  "herbal",
  "organic",
  "detox",
  "cleanse",
  "anti-aging",
  "wrinkles",
  "younger looking",
  "skin care",
  "acne",
  "blemish",
  "hair loss",
  "balding",
  "impotence",
  "ed",
  "erectile dysfunction",
  "enlarged prostate",
  "depression",
  "anxiety",
  "insomnia",
  "sleep",
  "sexually transmitted",
  "std",
  "hiv",
  "herpes",
  "aids",
  "cancer",
  "diabetes",
  "heart disease",
  "cholesterol",
  "blood pressure",
  "viagra",
  "cialis",
  "phentermine",
  "adipex",
  "valium",
  "xanax",
  "ambien",

  // Scam/Fraud Spam
  "nigerian prince",
  "inheritance",
  "lottery",
  "lotto",
  "claim prize",
  "prize",
  "congratulations",
  "you've won",
  "you won",
  "refund",
  "tax refund",
  "nigerian",
  "advance fee",
  "money transfer",
  "wire transfer",
  "banking details",
  "account details",
  "swiss account",
  "foreign account",
  "offshore",
  "secret",
  "confidential",
  "private",

  // Gambling/Adult Spam
  "casino",
  "poker",
  "blackjack",
  "slots",
  "roulette",
  "bet",
  "gambling",
  "adult",
  "xxx",
  "xxx content",
  "pornography",
  "porn",
  "nude",
  "sex",
  "webcam",
  "live chat",
  "dating",
  "singles",
  "hookup",
  "escort",

  // Tech Spam
  "software",
  "download",
  "virus",
  "malware",
  "spyware",
  "antivirus",
  "antispyware",
  "codec",
  "crack",
  "serial",
  "keygen",
  "torrent",
  "warez",
  "pirate",
  "free software",
  "freeware",
  "shareware",

  // General Spam Indicators
  "click",
  "link",
  "url",
  "http",
  "https",
  "www",
  ".com",
  ".net",
  ".org",
  "site",
  "website",
  "email",
  "reply",
  "respond",
  "contact",
  "message",
  "call",
  "phone",
  "sms",
  "text",
  "whatsapp",
  "telegram",
  "viber",
  "skype",

  // Spam Metrics/Pattern Words
  "congratulations",
  "dear",
  "valued",
  "customer",
  "dear customer",
  "dear friend",
  "dear sir",
  "dear madam",
  "dear user",
  "greetings",
  "hello",
  "hi",
  "dear recipient",
  "dear participant",

  // Currency & Payment Spam
  "usd",
  "pounds",
  "euros",
  "bitcoin",
  "cryptocurrency",
  "crypto",
  "payment",
  "credit card",
  "debit card",
  "paypal",
  "stripe",
  "bank",
  "banking",
  "atm",
  "check",
  "cheque",
  "money order",
  "western union",
  "moneygram",
  "swift",
  "routing number",
  "account number",
  "bsb",
  "sort code",
  "iban",
  "swift code",
];
